[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "first-athena-query"
version = "1.0.0"
description = "How to analyze millions of records in seconds with Amazon Web Services and SQL"
readme = "README.md"
requires-python = "==3.13.*"
license = "MIT"
dependencies = [
    "pandas",
    "boto3",
    "python-dateutil",
    "python-dotenv",
    "requests",
    "sphinx",
    "sphinx-autobuild",
    "myst-parser",
    "sphinx-palewire-theme",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]

[dependency-groups]
dev = [
    "pre-commit",
]

[tool.setuptools]
packages = []
py-modules = [
    "athena",
    "run",
]
